apiVersion: apps/v1
kind: Deployment
metadata:
  name: keand10
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keand10
  template:
    metadata:
      labels:
        app: keand10
    spec:
      containers:
      - image: okteto.dev/keand10:latest
        name: keand10
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "95507032-1760-47ac-acfa-ee71658a9137"
        - name: Vless_Path
          value: "/vlr3910"
        - name: Vmess_UUID
          value: "95507032-1760-47ac-acfa-ee71658a9137"
        - name: Vmess_Path
          value: "/vmr3910"
        - name: Share_Path
          value: "/v2link"
